"""empty message

Revision ID: 2b1807de3395
Revises: 
Create Date: 2019-08-06 17:43:45.970015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1807de3395'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('is_albums', sa.Integer(), nullable=True),
    sa.Column('is_attach', sa.Integer(), nullable=True),
    sa.Column('is_spec', sa.Integer(), nullable=True),
    sa.Column('sort_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example')
    # ### end Alembic commands ###
